name: mumm2020
channels:
  - damianavila82
  - satra
  - menpo
  - pluraldatum
  - glemaitre
  - soumith
  - conda-forge
  - defaults
  - simpleitk
dependencies:
  - python=3.6
  - numpy
  - matplotlib
  - pandas
  - notebook>=5.2.2
  - ipywidgets>=6.0.1
  - ipython>=6.2.1
  - pydot
  - h5py
  - scikit-image
  - scikit-learn
  - pytorch
  - torchvision
  - opencv3
  - tensorflow
  - itk
  - SimpleITK
  - ipyvolume
  - ffmpeg
  - graphviz
  - python-graphviz
  - pip
  - pip:
    - bokeh
    - keras==2.1.3
    - git+https://github.com/keras-team/keras-contrib
    - plotly
    - seaborn
    - tpot
    - pydot
    - dask_ndfilters
    - dask_ndmeasure
    - dask_ndmorph
    - distributed
    - psutil
    - kaggle
    - appmode
    - cloudpickle
    - autopep8
    - webcolors
    - jupyter_contrib_nbextensions
    - itkwidgets
    - rise
